{"name": "test_zone_europe_west3_x[project_vm_instances0]", "status": "broken", "statusDetails": {"message": "ValueError: Zone assertion not found for project_id '{'project_id': 'de0360-pkce-rubix-cl-dev000', 'zone': 'europe-west3-a', 'tags_assertion': True, 'labels_assertion': True, 'zone_assertion': 'europe-west3-x', 'deletion_protection_assertion': True, 'confidential_vm_service_assertion': False, 'display_device_assertion': False, 'no_gpu_assertion': True, 'persistent_boot_disk_assertion': True, 'secure_boot_assertion': True, 'vtpm_assertion': True, 'integrity_monitoring_assertion': True, 'cloud_platform_api_assertion': True, 'stackdriver_logging_api_assertion': True, 'storage_api_assertion': True, 'vm_provisioning_model_assertion': 'Standard', 'max_duration_assertion': 'None', 'on_host_maintenance_assertion': 'MIGRATE', 'automatic_restart_assertion': True, 'cpu_overcommit_assertion': False}' in the configuration YAML.", "trace": "self = <api_tests.test_rough2.TestComputeEngine object at 0x124a42b50>\nproject_vm_instances = [({'automatic_restart_assertion': True, 'cloud_platform_api_assertion': True, 'confidential_vm_service_assertion': Fal...f_link: \"https://www.googleapis.com/compute/v1/projects/de0360-pkce-rubix-cl-dev000/zones/europe-west3-a/instances\"\n>)]\n\n    @allure.story(\"Verify the zone for every Compute Engine VM Resource is europe-west3-x\")\n    @pytest.mark.parametrize(\"project_vm_instances\", [(p[\"project_id\"],) for p in config[\"projects\"]], indirect=True)\n    def test_zone_europe_west3_x(self, project_vm_instances):\n        for project_id, instances in project_vm_instances:\n            if not instances:\n                continue\n    \n            print(f\"Running test for Project ID: {project_id}\")\n    \n            zone_assertion = next((p[\"zone_assertion\"] for p in config[\"projects\"] if p[\"project_id\"] == project_id),\n                                  None)\n    \n            if zone_assertion is None:\n>               raise ValueError(f\"Zone assertion not found for project_id '{project_id}' in the configuration YAML.\")\nE               ValueError: Zone assertion not found for project_id '{'project_id': 'de0360-pkce-rubix-cl-dev000', 'zone': 'europe-west3-a', 'tags_assertion': True, 'labels_assertion': True, 'zone_assertion': 'europe-west3-x', 'deletion_protection_assertion': True, 'confidential_vm_service_assertion': False, 'display_device_assertion': False, 'no_gpu_assertion': True, 'persistent_boot_disk_assertion': True, 'secure_boot_assertion': True, 'vtpm_assertion': True, 'integrity_monitoring_assertion': True, 'cloud_platform_api_assertion': True, 'stackdriver_logging_api_assertion': True, 'storage_api_assertion': True, 'vm_provisioning_model_assertion': 'Standard', 'max_duration_assertion': 'None', 'on_host_maintenance_assertion': 'MIGRATE', 'automatic_restart_assertion': True, 'cpu_overcommit_assertion': False}' in the configuration YAML.\n\napi_tests/test_rough2.py:133: ValueError"}, "attachments": [{"name": "stdout", "source": "eb2b3a98-1678-42f8-81b2-014e52e246b8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "project_vm_instances", "value": "('de0360-pkce-rubix-cl-dev000',)"}], "start": 1690887787396, "stop": 1690887787397, "uuid": "5b3e6901-dd74-40ef-8967-26edc83fddbd", "historyId": "2e363ac56e36d9e6f5454ad487239dcd", "testCaseId": "f1fb05fc246ff80e08cdf79ca18b873a", "fullName": "api_tests.test_rough2.TestComputeEngine#test_zone_europe_west3_x", "labels": [{"name": "story", "value": "Verify the zone for every Compute Engine VM Resource is europe-west3-x"}, {"name": "feature", "value": "Compute Engine"}, {"name": "parentSuite", "value": "api_tests"}, {"name": "suite", "value": "test_rough2"}, {"name": "subSuite", "value": "TestComputeEngine"}, {"name": "host", "value": "192.168.1.49"}, {"name": "thread", "value": "42773-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_tests.test_rough2"}]}